### ISSUE TITLE
`TypeError: this.handleFetchCorrPlotImage is not a function`

### ISSUE THREAD

**Issue by krassowski** [genular/simon-frontend#118]
**Describe the bug**
`TypeError: this.handleFetchCorrPlotImage is not a function` bug shows up.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run SIMON with `svmLinear` and `naive_bayes` with default options + median imputation on cyclists.csv example dataset
2. Click analysis exploration
3. Select dataset then click on Clustering

```ts
                            TypeError: this.handleFetchCorrPlotImage is not a function
    at a.isTabEnabled (http://localhost:3010/6.b54b094e2455be5f79cc.js:1:4533)
    at a.mounted (http://localhost:3010/6.b54b094e2455be5f79cc.js:1:2506)
    at Ve (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1105790)
    at Jt (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1119748)
    at Object.insert (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1114770)
    at S (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1150745)
    at a.__patch__ (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1152145)
    at e._update (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1128902)
    at a.i (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1158999)
    at dn.get (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1121179)
```

```js
[{"message":{},"info":"vue-component-162-clusteringTab error in mounted hook","url":"http://localhost:3010/#/apps/simon/start-exploration","error":"TypeError: this.handleFetchCorrPlotImage is not a function\n    at a.isTabEnabled (http://localhost:3010/6.b54b094e2455be5f79cc.js:1:4533)\n    at a.mounted (http://localhost:3010/6.b54b094e2455be5f79cc.js:1:2506)\n    at Ve (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1105790)\n    at Jt (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1119748)\n    at Object.insert (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1114770)\n    at S (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1150745)\n    at a.__patch__ (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1152145)\n    at e._update (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1128902)\n    at a.i (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1158999)\n    at dn.get (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1121179)"},{"message":{},"info":"vue-component-162-clusteringTab error in activated hook","url":"http://localhost:3010/#/apps/simon/start-exploration","error":"TypeError: this.handleFetchCorrPlotImage is not a function\n    at a.isTabEnabled (http://localhost:3010/6.b54b094e2455be5f79cc.js:1:4533)\n    at a.activated (http://localhost:3010/6.b54b094e2455be5f79cc.js:1:2613)\n    at Ve (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1105790)\n    at Jt (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1119748)\n    at Zt (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1119639)\n    at Zt (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1119620)\n    at http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1120304\n    at cn (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1120316)\n    at Array.<anonymous> (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1106862)\n    at Ke (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1106262)"},{"message":{},"info":"vue-component-162-clusteringTab error in activated hook","url":"http://localhost:3010/#/apps/simon/start-exploration","error":"TypeError: this.handleFetchCorrPlotImage is not a function\n    at a.isTabEnabled (http://localhost:3010/6.b54b094e2455be5f79cc.js:1:4533)\n    at a.activated (http://localhost:3010/6.b54b094e2455be5f79cc.js:1:2613)\n    at Ve (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1105790)\n    at Jt (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1119748)\n    at Zt (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1119639)\n    at Zt (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1119620)\n    at http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1120304\n    at cn (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1120316)\n    at Array.<anonymous> (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1106862)\n    at Ke (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1106262)"},{"message":{},"info":"vue-component-162-clusteringTab error in activated hook","url":"http://localhost:3010/#/apps/simon/start-exploration","error":"TypeError: this.handleFetchCorrPlotImage is not a function\n    at a.isTabEnabled (http://localhost:3010/6.b54b094e2455be5f79cc.js:1:4533)\n    at a.activated (http://localhost:3010/6.b54b094e2455be5f79cc.js:1:2613)\n    at Ve (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1105790)\n    at Jt (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1119748)\n    at Zt (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1119639)\n    at Zt (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1119620)\n    at http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1120304\n    at cn (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1120316)\n    at Array.<anonymous> (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1106862)\n    at Ke (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1106262)"},{"message":{},"info":"vue-component-162-clusteringTab error in activated hook","url":"http://localhost:3010/#/apps/simon/start-exploration","error":"TypeError: this.handleFetchCorrPlotImage is not a function\n    at a.isTabEnabled (http://localhost:3010/6.b54b094e2455be5f79cc.js:1:4533)\n    at a.activated (http://localhost:3010/6.b54b094e2455be5f79cc.js:1:2613)\n    at Ve (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1105790)\n    at Jt (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1119748)\n    at Zt (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1119639)\n    at Zt (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1119620)\n    at http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1120304\n    at cn (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1120316)\n    at Array.<anonymous> (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1106862)\n    at Ke (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1106262)"},{"message":{},"info":"vue-component-162-clusteringTab error in activated hook","url":"http://localhost:3010/#/apps/simon/start-exploration","error":"TypeError: this.handleFetchCorrPlotImage is not a function\n    at a.isTabEnabled (http://localhost:3010/6.b54b094e2455be5f79cc.js:1:4533)\n    at a.activated (http://localhost:3010/6.b54b094e2455be5f79cc.js:1:2613)\n    at Ve (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1105790)\n    at Jt (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1119748)\n    at Zt (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1119639)\n    at Zt (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1119620)\n    at http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1120304\n    at cn (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1120316)\n    at Array.<anonymous> (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1106862)\n    at Ke (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1106262)"},{"message":{},"info":"vue-component-162-clusteringTab error in activated hook","url":"http://localhost:3010/#/apps/simon/start-exploration","error":"TypeError: this.handleFetchCorrPlotImage is not a function\n    at a.isTabEnabled (http://localhost:3010/6.b54b094e2455be5f79cc.js:1:4533)\n    at a.activated (http://localhost:3010/6.b54b094e2455be5f79cc.js:1:2613)\n    at Ve (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1105790)\n    at Jt (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1119748)\n    at Zt (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1119639)\n    at Zt (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1119620)\n    at http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1120304\n    at cn (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1120316)\n    at Array.<anonymous> (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1106862)\n    at Ke (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1106262)"},{"message":{},"info":"vue-component-162-clusteringTab error in activated hook","url":"http://localhost:3010/#/apps/simon/start-exploration","error":"TypeError: this.handleFetchCorrPlotImage is not a function\n    at a.isTabEnabled (http://localhost:3010/6.b54b094e2455be5f79cc.js:1:4533)\n    at a.activated (http://localhost:3010/6.b54b094e2455be5f79cc.js:1:2613)\n    at Ve (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1105790)\n    at Jt (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1119748)\n    at Zt (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1119639)\n    at Zt (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1119620)\n    at http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1120304\n    at cn (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1120316)\n    at Array.<anonymous> (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1106862)\n    at Ke (http://localhost:3010/vendor.bundle.103450cd5c7f8235adf1.js:2:1106262)"}]
```

**Desktop (please complete the following information):**
*If applicable, eg. Interface issue*
 - OS: Ubuntu
 - Browser Edge
 - Version 102

**Additional context**
Reproduced on Firefox running on Windows by @atomiclaboratory during a workshop today.

**Comment by TheGalgut** [comment]
I have had the same problem running SIMON on windows in Edge or Chrome
